spring:
  debug: true
  datasource:
    url: jdbc:postgresql://localhost:5432/rrhh
    username: rrhh
    password: admin
    initialization-mode: always
#    data: classpath*:sql/dataOld.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    property-naming-strategy: SNAKE_CASE
server:
  port: 8100

